version: "2"
services:

  aggregation1:
    image: go_rtb_agg
    environment:
      RTBAGG_ESAGGURL: "http://10.0.0.12:9200"
      RTBAGG_MYSQLHOST: "10.0.0.12"
      RTBAGG_MYSQLUSER: "ben"
      RTBAGG_MYSQLPASSWORD: "test"
      RTBAGG_MYSQLDBNAME: "rtb4free"
      RTBAGG_ENABLEDOMAINAGG: "true"
      RTBAGG_ESAGGINDEX: "bidagg"
      RTBAGG_ESAGGDOMAININDEX: "domainagg"
      RTBAGG_BROKERLIST: "kafka:9092"
      RTBAGG_ENABLEAGGARRAYSEND: "false"
      RTBAGG_DEBUG: "false"
